apiVersion: v1
data:
  korrel8r.yaml: |
    # Default configuration for deploying Korrel8r as a service in an OpenShift cluster.
    # Store service URLs assume that stores are installed in their default locations.
    stores:
      - domain: k8s
      - domain: alert
        metrics: https://thanos-querier.openshift-monitoring.svc:9091
        alertmanager: https://alertmanager-main.openshift-monitoring.svc:9094
        certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      - domain: log
        lokiStack: https://logging-loki-gateway-http.openshift-logging.svc:8080
        certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      - domain: metric
        metric: https://thanos-querier.openshift-monitoring.svc:9091
        certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      - domain: netflow
        lokiStack: https://loki-gateway-http.netobserv.svc:8080
        certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      - domain: trace
        tempoStack: https://tempo-platform-gateway.openshift-tracing.svc.cluster.local:8080/api/traces/v1/platform/tempo/api/search
        certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt

    include:
      - /etc/korrel8r/rules/all.yaml
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-11T12:58:43Z"
  labels:
    app.kubernetes.io/instance: korrel8r
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/name: korrel8r
    app.kubernetes.io/part-of: UIPlugin
  name: korrel8r
  namespace: openshift-cluster-observability-operator
  ownerReferences:
  - apiVersion: observability.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: UIPlugin
    name: troubleshooting-panel
    uid: 1f5e5654-c0a4-4087-b61b-68ad29a2d812
  resourceVersion: "1198124688"
  uid: df1563e9-a04c-45cf-9e06-2da3ccd32712
