apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-data","namespace":"minio-demo"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"60Gi"}},"storageClassName":"nfs-csi"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
    volume.kubernetes.io/storage-provisioner: nfs.csi.k8s.io
  creationTimestamp: "2026-09-11T12:54:21Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: minio-data
  namespace: minio-demo
  resourceVersion: "1198116685"
  uid: d460942f-7754-4b2d-946f-1b4c0874e8e2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
  volumeName: pvc-d460942f-7754-4b2d-946f-1b4c0874e8e2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 60Gi
  phase: Bound
