apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.1.227/23"],"mac_address":"0a:58:0a:81:01:e3","gateway_ips":["10.129.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.129.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.129.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.129.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.129.0.1"}],"ip_address":"10.129.1.227/23","gateway_ip":"10.129.0.1","role":"primary"}}'
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "ovn-kubernetes",
            "interface": "eth0",
            "ips": [
                "10.129.1.227"
            ],
            "mac": "0a:58:0a:81:01:e3",
            "default": true,
            "dns": {}
        }]
      openshift.io/scc: restricted-v2
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
      security.openshift.io/validated-scc-subject-type: user
    creationTimestamp: "2026-09-11T12:54:30Z"
    generateName: minio-85955fbf95-
    generation: 1
    labels:
      app: minio
      pod-template-hash: 85955fbf95
    name: minio-85955fbf95-qj6g8
    namespace: minio-demo
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: minio-85955fbf95
      uid: a1813f52-c253-4df9-a149-7eb2f034379e
    resourceVersion: "1198117578"
    uid: 2715d56f-d05a-4cce-807d-6738d09ed1ef
  spec:
    containers:
    - args:
      - minio server /data --console-address :9001
      command:
      - /bin/bash
      - -c
      envFrom:
      - secretRef:
          name: minio-root-credentials
      image: quay.io/minio/minio:latest
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /minio/health/live
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: minio
      ports:
      - containerPort: 9000
        name: api
        protocol: TCP
      - containerPort: 9001
        name: console
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /minio/health/ready
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1001610000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-5g29b
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    imagePullSecrets:
    - name: default-dockercfg-wqzrs
    nodeName: 80-18-44-f0-71-30
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1001610000
      seLinuxOptions:
        level: s0:c40,c25
      seccompProfile:
        type: RuntimeDefault
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: minio-data
    - name: kube-api-access-5g29b
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
        - configMap:
            items:
            - key: service-ca.crt
              path: service-ca.crt
            name: openshift-service-ca.crt
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-09-11T12:54:51Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-09-11T12:54:30Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-09-11T12:54:57Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-09-11T12:54:57Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-09-11T12:54:30Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: cri-o://d9c2db0ab37b15f841334aac306ccd272c1fb2ffe1a6429b8e4b8a8b38d6baa7
      image: quay.io/minio/minio:latest
      imageID: quay.io/minio/minio@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
      lastState: {}
      name: minio
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-09-11T12:54:50Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          - 1001610000
          uid: 1001610000
      volumeMounts:
      - mountPath: /data
        name: data
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-5g29b
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.16.1.4
    hostIPs:
    - ip: 172.16.1.4
    phase: Running
    podIP: 10.129.1.227
    podIPs:
    - ip: 10.129.1.227
    qosClass: BestEffort
    startTime: "2026-09-11T12:54:30Z"
kind: List
metadata:
  resourceVersion: ""
