apiVersion: v1
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"operators.coreos.com/v1","kind":"OperatorGroup","metadata":{"annotations":{},"name":"openshift-operators-redhat","namespace":"openshift-operators-redhat"},"spec":{}}
    creationTimestamp: "2026-09-11T12:52:49Z"
    generation: 1
    name: openshift-operators-redhat
    namespace: openshift-operators-redhat
    resourceVersion: "1198113447"
    uid: fa9fc9ef-92a6-4b28-8521-80d441f9639a
  spec:
    upgradeStrategy: Default
  status:
    lastUpdated: "2026-09-11T12:52:49Z"
    namespaces:
    - ""
kind: List
metadata:
  resourceVersion: ""
