# S3 storage secret pointing at the in-cluster MinIO instance already
# running in minio-demo (bucket "loki-logging" pre-created by minio-mc-mb job).
apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  bucketnames: loki-logging
  endpoint: http://minio.minio-demo.svc:9000
  access_key_id: <REDACTED>
  access_key_secret: <REDACTED>
  region: us-east-1
type: Opaque
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
      - version: v13
        effectiveDate: '2024-01-01'
    secret:
      name: logging-loki-s3
      type: s3
  storageClassName: nfs-csi
  tenants:
    mode: openshift-logging
