apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"loki-operator","namespace":"openshift-operators-redhat"},"spec":{"channel":"stable-6.6","installPlanApproval":"Automatic","name":"loki-operator","source":"redhat-operators","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2026-09-11T13:00:30Z"
  generation: 1
  labels:
    operators.coreos.com/loki-operator.openshift-operators-redhat: ""
  name: loki-operator
  namespace: openshift-operators-redhat
  resourceVersion: "1198131314"
  uid: 4edeb882-b83f-46a0-aed3-aa423f2a0ab4
spec:
  channel: stable-6.6
  installPlanApproval: Automatic
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "1198123860"
      uid: ac33f395-0afb-4228-848d-16cc793a1c39
    healthy: true
    lastUpdated: "2026-09-11T13:00:40Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "1198123862"
      uid: 8ece5c23-9986-4972-a9ec-0e6351c6d26b
    healthy: true
    lastUpdated: "2026-09-11T13:00:40Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-marketplace
      namespace: openshift-marketplace
      resourceVersion: "1198123888"
      uid: 833baeb6-386a-49fa-b087-66e61f295909
    healthy: true
    lastUpdated: "2026-09-11T13:00:40Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "1198118779"
      uid: 7a29ceb5-b1ad-4a8f-838b-b4f66a4b1c92
    healthy: true
    lastUpdated: "2026-09-11T13:00:40Z"
  conditions:
  - lastTransitionTime: "2026-09-11T13:00:43Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  currentCSV: loki-operator.v6.6.1
  installPlanGeneration: 1
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-8wsrj
    namespace: openshift-operators-redhat
    resourceVersion: "1198129500"
    uid: 822692a2-2c3c-430b-ba2f-1750b7fa5672
  installedCSV: loki-operator.v6.6.1
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-8wsrj
    uuid: 822692a2-2c3c-430b-ba2f-1750b7fa5672
  lastUpdated: "2026-09-11T13:01:45Z"
  state: AtLatestKnown
