apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"observability.openshift.io/v1alpha1","kind":"UIPlugin","metadata":{"annotations":{},"name":"logging"},"spec":{"logging":{"logsLimit":50,"lokiStack":{"name":"logging-loki"},"timeout":"30s"},"type":"Logging"}}
    observability.openshift.io/api-support: GeneralAvailability
  creationTimestamp: "2026-09-11T13:07:44Z"
  generation: 1
  name: logging
  resourceVersion: "1198151975"
  uid: 7dbaf4c9-b3e7-4eb9-86d3-cc951b101da3
spec:
  logging:
    logsLimit: 50
    lokiStack:
      name: logging-loki
    timeout: 30s
  type: Logging
status:
  conditions:
  - lastTransitionTime: "2026-09-11T13:13:03Z"
    message: ""
    observedGeneration: 1
    reason: UIPluginReconciled
    status: "False"
    type: Degraded
  - lastTransitionTime: "2026-09-11T13:13:03Z"
    message: Plugin reconciled successfully
    observedGeneration: 1
    reason: UIPluginReconciled
    status: "True"
    type: Reconciled
  - lastTransitionTime: "2026-09-11T13:13:03Z"
    message: ""
    observedGeneration: 1
    reason: UIPluginAvailable
    status: "True"
    type: Available
